### ISSUE TITLE
[BUG] ssr rendering on netlify (rimraf issue)

### ISSUE THREAD

**Issue by slk333** [Luehang/react-paypal-button-v2#23]
the version 2.4 didn't build on Netlify because your module tries to use rimraf without linking it as a dependency.
`npm install rimraf -s`
fixed it.

**Comment by Luehang** [comment]
Hi,

What is your use case?  Those commands are only development purposes and the package should come completely compiled.

**Comment by slk333** [comment]
```

2:58:40 PM: > react-paypal-button-v2@2.4.0 preinstall /opt/build/repo/node_modules/react-paypal-button-v2
2:58:40 PM: > rimraf dist

```
In the build log, Netlify uses rimraf.
Before I installed manually, it would crash since rimraf was not installed.

I have no idea why Netlify uses rimraf to install your module!

**Comment by slk333** [comment]
a different output that might help also:
```
2:35:49 PM: error /opt/build/repo/node_modules/react-paypal-button-v2: Command failed.
2:35:49 PM: Exit code: 127
2:35:49 PM: Command: rimraf dist
2:35:49 PM: Arguments:
2:35:49 PM: Directory: /opt/build/repo/node_modules/react-paypal-button-v2
2:35:49 PM: Output:
2:35:49 PM: /bin/sh: 1: rimraf: not found
```

**Comment by pateljigar053** [comment]
I am experiencing the same issue. Please help.

error /builds/starr-project/tax-collector-registry/node_modules/react-paypal-button-v2: Command failed.
Exit code: 127
Command: rimraf dist
Arguments: 
Directory: /builds/starr-project/tax-collector-registry/node_modules/react-paypal-button-v2
Output:
/bin/sh: 1: rimraf: not found
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

**Comment by pateljigar053** [comment]
I am experiencing the same issue. Please help.

`error /builds/starr-project/tax-collector-registry/node_modules/react-paypal-button-v2: Command failed.
Exit code: 127
Command: rimraf dist
Arguments: 
Directory: /builds/starr-project/tax-collector-registry/node_modules/react-paypal-button-v2
Output:
/bin/sh: 1: rimraf: not found
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.`

**Comment by slk333** [comment]
try
`yarn global add rimraf`

**Comment by checor** [comment]
I'm experiencing the same problem on the latest release. Does installing rimraf global is a solution to for netlify? I'm currently not using it but I will use it in the future.

**Comment by mtlewando** [comment]
Just encountered the same issue doing a local installation. Presumably `rimraf` is used without being required as a dependency. Fixed by locally / globally installing `rimraf` as above.

**Comment by slk333** [comment]
@Luehang can you add rimraf as a dependency? thanks!

**Comment by Luehang** [comment]
Hi,

Install latest to solve that platform error.  Thanks.

## :large_blue_diamond: Install

```sh
$ npm install react-paypal-button-v2@2.4.1 --save
```

or

```sh
$ yarn add react-paypal-button-v2@2.4.1
```

**Comment by fablanglet** [comment]
Hello,

I still have the issue with 2.4.1 using GitLab CI
Should I install package by myself?

Thank you

**Comment by kyliepace** [comment]
same.

**Comment by Luehang** [comment]
Hi,

You could try installing the `rimraf` package first.

```sh
$ npm install rimraf --save
```

or

```sh
$ yarn add rimraf
```

Let me know if that works!

**Comment by Raghav-Maheshwari** [comment]
@Luehang 

Having trouble compiling the latest version of this package @2.6.0 on Heroku as well because rimraf is missing:

```
> rimraf dist
sh: 1: rimraf: not found
```

**Comment by howdyhyber** [comment]
I also encountered this issue.

It works fine in local machine but when i deploy my app to production, it will not work.

**Comment by GabinhoJean** [comment]
Hi everyone.

I also have this issue. 

When its works locally but not online.

 i am using the version 2.6.0 of react-paypal-button-v2.

i tried to change the version for one more old like 2.4.1 and i tried to install manually rimraf  with the command:
 npm install rimraf --save 
but the problem is not solved

**Comment by Luehang** [comment]
Hi,

Install latest to solve that error.  Thanks.

## :large_blue_diamond: Install

```sh
$ npm install react-paypal-button-v2@2.6.1 --save
```

or

```sh
$ yarn add react-paypal-button-v2@2.6.1
```

**Comment by howdyhyber** [comment]
It works! Thank you for the response!
